YEAR_DROPDOWN = "year-dropdown"
MONTH_DROPDOWN = "month-dropdown"
COMPANY_DROPDOWN = "company-dropdown"
SELECT_ALL_YEARS_BUTTON = "select-all-years-button"
SELECT_ALL_MONTHS_BUTTON = "select-all-months-button"
SELECT_ALL_COMPANIES_BUTTON = "select-all-companies-button"
BAR_CHART = "bar-chart"
PIE_CHART = "pie-chart"
